name: AdminSounds
version: '1.0'
main: com.axteroid.AdminSound
api-version: '1.20'
authors: [Axteroid]
description: A plugin for making & playing custom sound effects with config support!
softdepend: [ItemsAdder, Oraxen, NexoPlugins]
commands:
  adminsounds:
    description: Main command for AdminSounds plugin
    aliases: [asounds, as]
    permission: adminsounds.use
    usage: |-
      &#4e5de6&l╔════════ &f&lAdmin&bSounds &r&#4e5de6&l════════╗
      &#00bfff➤ &f/adminsounds play <player> <sound> &7- Play a sound effect
      &#00bfff➤ &f/adminsounds playall <sound> &7- Play a sound effect to everyone
      &#00bfff➤ &f/adminsounds list &7- List available sound effects
      &#00bfff➤ &f/adminsounds reload &7- Reload the configuration
      &#00bfff➤ &f/adminsounds debug <sound> &7- Debug sound effect timing
      &#4e5de6&l╚══════════════════════════╝

permissions:
  adminsounds.use:
    description: Allows using the basic AdminSounds commands
    default: op
  adminsounds.play:
    description: Allows playing sounds on yourself
    default: op
  adminsounds.play.others:
    description: Allows playing sounds on other players
    default: op
  adminsounds.playall:
    description: Allows playing sounds for all online players
    default: op
  adminsounds.reload:
    description: Allows reloading the plugin configuration
    default: op
  adminsounds.debug:
    description: Allows using debug commands
    default: op
    adminsounds.*:
      description: Gives access to all AdminSounds commands
      children:
        adminsounds.use: true
        adminsounds.reload: true
        adminsounds.play: true
        adminsounds.play.others: true
        adminsounds.playall: true
        adminsounds.debug: true